CREATE TABLE IF NOT EXISTS `gmt_redirection_summary` (
  dated DATE,
  unionk CHAR(32) NOT NULL DEFAULT '',
  campaign_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  group_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  aff_id SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  aff_pub VARCHAR(255) NOT NULL DEFAULT "",
  redirection_type CHAR(4) NOT NULL DEFAULT "R000",
  gross_cnt INT(11) UNSIGNED NOT NULL DEFAULT 0,
  last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(dated, unionk),
  KEY gmt_redirection_summary_campaign_id(campaign_id),
  KEY gmt_redirection_summary_group_id(group_id),
  KEY gmt_redirection_summary_redirection_type(redirection_type),
  KEY gmt_redirection_summary_affiliate(aff_id, aff_pub)
) ENGINE=InnoDB CHARSET=utf8
PARTITION BY RANGE(TO_DAYS(dated)) (
  PARTITION p0 VALUES LESS THAN (TO_DAYS("2017-10-01")),
  PARTITION p1 VALUES LESS THAN (TO_DAYS("2018-01-01")),
  PARTITION p2 VALUES LESS THAN (TO_DAYS("2018-04-01")),
  PARTITION p3 VALUES LESS THAN (TO_DAYS("2018-07-01")),
  PARTITION p4 VALUES LESS THAN (TO_DAYS("2018-10-01")),
  PARTITION p5 VALUES LESS THAN (TO_DAYS("2019-01-01")),
  PARTITION p6 VALUES LESS THAN (TO_DAYS("2019-04-01")),
  PARTITION p7 VALUES LESS THAN (TO_DAYS("2019-07-01")),
  PARTITION p8 VALUES LESS THAN (TO_DAYS("2019-10-01")),
  PARTITION p9 VALUES LESS THAN (TO_DAYS("2020-01-01")),
  PARTITION p10 VALUES LESS THAN (TO_DAYS("2020-04-01")),
  PARTITION p11 VALUES LESS THAN (TO_DAYS("2020-07-01")),
  PARTITION p12 VALUES LESS THAN (TO_DAYS("2020-10-01")),
  PARTITION p13 VALUES LESS THAN (TO_DAYS("2099-01-01"))
);
